version: '3.3'
services:
  redis:
    image: redis:6.0.7
    container_name: redis
    hostname: "127.0.0.1"
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: 
      context: ./App
    depends_on:
      - redis
      - mongodb

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_volume_data:/db
    
volumes:
  redis_volume_data:
  redis_insight_volume_data:
  mongodb_data: